# Generated by Django 4.1.3 on 2023-11-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Operacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operacion", models.CharField(max_length=255)),
                ("resultado", models.FloatField()),
            ],
        ),
    ]
